services:
  sharehouseplan:
    build:
      context: ../
      dockerfile: ./docker-build/Dockerfile
    container_name: ShareHousePlan
    restart: always
    volumes:
      - ./datas:/app/datas
    ports:
      - 8080:8080
