services:
  sharehouseplan:
    build:
      context: ../
      dockerfile: ./docker-build/Dockerfile
    container_name: ShareHousePlan-build
    restart: always
    volumes:
      - ../docker/DATAS/datas:/app/datas
    ports:
      - 8080:8080
